config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :sessions, only: [:create, :destroy]

  get 'login', to: "sessions#create", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'

  root to: "posts#index"

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user, foreign_key: :author_id
	before_save :convert_text

	validates :title, presence: true

	def delay_publishing(due_string)
		self.publish_status = 0
		PublishingWorker.perform_at(eval(due_string).from_now, self.id)
		return self
	end

	private
	def convert_text
		self.converted_text = MarkdownProcessorWorker.new.perform(self.markdown_text)
	end

end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	validates :email, presence: true
	validates :email, format: /.+@.+\..+/i
	validates :password, confirmation: true
	validates :password, length: { minimum: 6 }
	validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

	def logged_in?
	  @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def get_user_name
		@current_user.name unless @current_user.nil?
	end

	def verify_authentication
		redirect_to root_url, notice: "You are not logged in" unless logged_in?
	end

	helper_method :logged_in?
	helper_method :get_user_name
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :verify_authentication, except: [:index, :show]
	
	def index
		@posts = Post.where("publish_status = 1")
	end

	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(allowed_params)
		@post.author_id = @current_user.id

		if params[:schedule].eql?("0") && @post.save(allowed_params)
			redirect_to @post, notice: 'Post created!'
		elsif @post.delay_publishing(params[:schedule]).save(allowed_params)
			redirect_to root_url, notice: 'Post publishing scheduled!'
		else
			render :new
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if params[:schedule].eql?("0") && @post.update(allowed_params)
			redirect_to @post, notice: 'Post updated!'
		elsif @post.delay_publishing(params[:schedule]).update(allowed_params)
			redirect_to root_url, notice: 'Post update scheduled!'
		else
			render :edit
		end
	end

	private

	def allowed_params
		params.require(:post).permit(:author_id, :title, :markdown_text, :schedule)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
		user = User.find_by(email: params[:email])

		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to root_url, notice: 'Welcome!'
		else
			redirect_to root_url, notice: 'Wrong email or password'
		end
	end

	def destroy
		session[:user_id] = nil
  	redirect_to root_url, notice: 'Logged out!'
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_login_header.html.erb
<div class="row">
	<div class="col-md-4">
		<h1>TechBlog 2.0</h1>
	</div>
	<div class="col-md-8">
		<% if logged_in? %>
			<div class="pull-right top-buffer">
				<span class="right-buffer">Welcome, <%= get_user_name %></span>
				<%= link_to "Logout", logout_path, class: "btn btn-danger" %>
			</div>
		<% else %>
			<div class="pull-right">
					<%= form_tag('/sessions', method: :create, class: "form-inline") do %>
						<div class="form-group top-buffer">
							<%= text_field_tag :email, "", class: "form-control", placeholder: "Email" %>
							<%= text_field_tag :password, "", class: "form-control", placeholder: "Password" %>
				    	<%= submit_tag "Login", class: "btn btn-primary" %>
						</div>
					<% end %>
			</div>
		<% end %>
	</div>
</div>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Techblog</title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= action_cable_meta_tag %>
  </head>

  <body class="container base-color">
    <%= bootstrap_flash %>
    <%= render "layouts/login_header" %>
    <div class="post-area bottom-buffer">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<%= form_with model: @post, local: true do |f| %>
			<div class="form-group">
				<%= f.label :title %>
				<%= f.text_field :title, class: "form-control form-control-sm" %><br><br>
				<%= f.label :Text %>
				<%= render "markdown_tools" %>
				<%= f.text_area :markdown_text, id: :markdown_text, size: "100x15", class: "form-control form-control-sm" %>
				<p id="preview_screen" class="top-buffer bottom-buffer"></p>
				<input type="button" name="preview" id="preview_button" class="btn btn-primary" value="Preview">

				<div class="input-group pull-right">
			    <select class="custom-select form-control" name="schedule" id="schedule">
				    <option value="0" selected>Now</option>
				    <option value="10.seconds">10 secs</option>
				    <option value="30.seconds">30 secs</option>
				    <option value="1.minute">1 min</option>
				    <option value="10.minutes">10 min</option>
				  </select>
				</div>
		    <%= f.submit "Publish", class: "btn btn-success pull-right" %>
		<% end %>
	</div>
</div>
<script type="text/javascript">
	var markdown_text = document.getElementById("markdown_text");
	var preview_button = document.getElementById("preview_button");
	preview_button.addEventListener("click", function() {
		App.markdown_conversion.convert(markdown_text.value);
	});
	var preview_screen = document.getElementById("preview_screen");
	document.addEventListener("markdown_conversion_channel", function(e) {
		preview_screen.innerHTML = e.detail
	});
</script>

app/views/posts/_markdown_tools.html.erb
<div class="row" style="margin-left: 10px; margin-bottom: 5px;">
	<button type="button" id="h1" class="btn btn-info tool" style="font-size: 18px; padding-left: 7px;">H1</button>
	<button type="button" id="h2" class="btn btn-info tool" style="font-size: 14px; padding-left: 8px;">H2</button>
	<button type="button" id="h3" class="btn btn-info tool" style="font-size: 12px; padding-left: 9px;">H3</button>
	<button type="button" id="h4" class="btn btn-info tool" style="font-size: 10px; padding-left: 10px;">H4</button>
	<button type="button" id="h5" class="btn btn-info tool" style="font-size: 9px;">H5</button>
	<button type="button" id="h6" class="btn btn-info tool" style="font-size: 8px;">H6</button>
	<button type="button" id="i" class="btn btn-info tool"><i>I</i></button>
	<button type="button" id="b" class="btn btn-info tool"><b>B</b></button>
	<button type="button" id="s" class="btn btn-info tool"><s>S</s></button>
	<button type="button" id="list" class="btn btn-info tool">1.</button>
	<button type="button" id="link" class="btn btn-info tool" style="font-size: 18px; padding-left: 7px;">&lt;&gt;</button>
	<button type="button" id="img" class="btn btn-info tool" style="padding-left: 3px;">img</button>
	<button type="button" id="code" class="btn btn-info tool" style="font-size: 10px; padding-left: 5px;">code</button>
	<button type="button" id="quote" class="btn btn-info tool" style="font-size: 10px; padding-left: 2px;">quote</button>
</div>
<script type="text/javascript">
	function elid(id) { return document.getElementById(id); }

	function toolAction(text_element, markdown_text, selection_start, selection_end) {
		var sel = text_element.selectionEnd;
		text_element.value = text_element.value.substring(0, sel) + markdown_text + text_element.value.substring(sel, text_element.length);
		text_element.focus();
		text_element.setSelectionRange(sel+selection_start, sel+selection_start+selection_end)
	}

	elid("h1").onclick = function() { toolAction(elid("markdown_text"), "\n# TITLE", 3, 5); }
	elid("h2").onclick = function() { toolAction(elid("markdown_text"), "\n## TITLE", 4, 5); }
	elid("h3").onclick = function() { toolAction(elid("markdown_text"), "\n### TITLE", 5, 5); }
	elid("h4").onclick = function() { toolAction(elid("markdown_text"), "\n#### TITLE", 6, 5); }
	elid("h5").onclick = function() { toolAction(elid("markdown_text"), "\n##### TITLE", 7, 5); }
	elid("h6").onclick = function() { toolAction(elid("markdown_text"), "\n###### TITLE", 8, 5); }
	elid("i").onclick = function() { toolAction(elid("markdown_text"), "*TEXT*", 1, 4); }
	elid("b").onclick = function() { toolAction(elid("markdown_text"), "**TEXT**", 2, 4); }
	elid("s").onclick = function() { toolAction(elid("markdown_text"), "~~TEXT~~", 2, 4); }
	elid("list").onclick = function() { toolAction(elid("markdown_text"), "\n1. ITEM\n2. ITEM\n3. ITEM\n", 4, 4); }
	elid("link").onclick = function() { toolAction(elid("markdown_text"), "[TEXT](LINK)", 1, 4); }
	elid("img").onclick = function() { toolAction(elid("markdown_text"), "![TEXT](IMAGE_LINK \"TITLE\")", 2, 4); }
	elid("code").onclick = function() { toolAction(elid("markdown_text"), "`CODE`", 1, 4); }
	elid("quote").onclick = function() { toolAction(elid("markdown_text"), "\n> TEXT", 3, 4); }
</script>

app/views/posts/edit.html.erb
<div class="row" style="padding-top: 10px;">
  <div class="col-md-10 col-md-offset-1">
    <%= link_to 'Back', post_path(@post), class: "btn btn-danger" %>
  </div>
</div>
<h1 class="title">Edit post</h1>
<%= render "form" %>

app/views/posts/index.html.erb
<div class="row" style="padding-top: 10px;">
	<% if logged_in? %>
		<div class="pull-right">
			<%= link_to "New Post", new_post_path, class: "btn btn-success" %>
		</div>
	<% end %>
  <% @posts.each do |post| %>
    <div class="row left-buffer bottom-buffer" style="width: 90%">
      <div class="col-md-12 left-buffer highlight" style="text-align: center;">
  		  <h2 class="title"><a href="<%= post_path(post) %>"><%= post.title %></a></h2>
        <small><i>Created at:</i> <%= post.created_at.to_s[0..10] %></small>
        <small><i>By:</i> <%= post.user.name %></small>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="row" style="padding-top: 10px;">
  <div class="col-md-10 col-md-offset-1">
    <%= link_to 'Back', posts_path, class: "btn btn-danger" %>
  </div>
</div>
<h1 class="title">New post</h1>
<%= render "form" %>

app/views/posts/show.html.erb
<div class="row left-buffer" style="padding-top: 10px;">
  <div class="col-md-10 col-md-offset-1">
  <% if logged_in? %>
    <%= link_to "Edit", edit_post_path(@post), class: "btn btn-success pull-right" %>
  <% end %>
  <%= link_to 'Back', posts_path, class: "btn btn-danger" %>
  </div>
</div>
<div class="row left-buffer">
  <div class="col">
    <h1 class="title"><%= @post.title %></h1>
  </div>
</div>
<div class="row left-buffer">
  <div class="col-md-8 col-md-offset-2" style="text-align: center;">
    <small class="right-buffer"><i>Created at:</i> <%= @post.created_at.to_s[0..10] %></small>
    <small class="right-buffer"><i>Last update:</i> <%= @post.updated_at.to_s[0..10] %></small>
    <small><i>By:</i> <%= @post.user.name %></small>
  </div>
</div>
<div class="row left-buffer">
  <div class="col-md-10 col-md-offset-1">
    <%= @post.converted_text.html_safe %>
  </div>
</div>